version: '1.0'

services:
  ur_ros2_base:
    image: savicktso/ur_ros2_2024:humble
    container_name: ur10e_base
    network_mode: host
    ipc: host
    pid: host
    stdin_open: true
    tty: true
    restart: no
    command: ["/bin/bash", "-c", "export ROS_DOMAIN_ID=1 && export ROS_MASTER_URI=1 && ros2 launch ur_robot_driver ur_control.launch.py ur_type:=ur10e robot_ip:=192.168.1.102 use_fake_hardware:=true launch_rviz:=false "]

  ur_ros2_moveit:
    image: savicktso/ur_ros2_2024:humble
    container_name: ur10e_moveit
    network_mode: host
    ipc: host
    pid: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    restart: no
    command: ["/bin/bash", "-c", "export ROS_DOMAIN_ID=1 && export ROS_MASTER_URI=1 && ros2 launch ur_moveit_config ur_moveit.launch.py ur_type:=ur10e launch_rviz:=true use_sim_time:=false"]

  ur_ros2_cartesianmove:
    image: savicktso/ur_ros2_2024:humble
    container_name: ur_bash
    network_mode: host
    ipc: host
    pid: host
    volumes:
      - ./../hello_moveit_ur/:/root/ros2_ws/src/hello_moveit_ur/
    stdin_open: true
    tty: true
    restart: no
    command: ["/bin/bash", "-c", "export ROS_DOMAIN_ID=1 && export ROS_MASTER_URI=1 && cd /root/ros2_ws && colcon build && source install/setup.bash && ros2 launch hello_moveit_ur hello_moveit_ur_launch.py"]

  ur_ros2_bash:
    image: savicktso/ur_ros2_2024:humble
    container_name: ur_bash
    network_mode: host
    ipc: host
    pid: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./../hello_moveit_ur/:/root/ros2_ws/src/hello_moveit_ur/
    stdin_open: true
    tty: true
    restart: no
    command: ["/bin/bash"]