# Use the official ROS 2 base image
FROM osrf/ros:humble-desktop

# Install necessary packages
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    ros-humble-moveit \
    ros-humble-ur=2.2.16-5jammy.20241029.212959 \
    && apt-get upgrade -y

RUN echo 'source /opt/ros/humble/setup.bash' >> ~/.bashrc